LUCAS EE

https://developers.google.com/earth-engine/datasets/catalog/JRC_LUCAS_HARMO_THLOC_V1#citations

In [1]:
import ee
import geemap
import pandas as pd
import geopandas as gpd
import json
import os

# Run as service account
service_account = '...com'
credentials = ee.ServiceAccountCredentials(service_account, '.private-key.json')

ee.Initialize(credentials)

Map = geemap.Map(center=[43.7196, 10.4250], zoom=5)
# Map

In [2]:
ee_fc = ee.FeatureCollection({'type': 'FeatureCollection',
 'columns': {'system:index': 'String'},
 'features': [{'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [10.390273, 43.719001]},
   'id': '0',
   'properties': {}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [10.410183, 43.719497]},
   'id': '1',
   'properties': {}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [10.481584, 43.741329]},
   'id': '2',
   'properties': {}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [10.393706, 43.746289]},
   'id': '3',
   'properties': {}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [10.384094, 43.691204]},
   'id': '4',
   'properties': {}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [10.52827, 43.710564]},
   'id': '5',
   'properties': {}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [10.430093, 43.702126]},
   'id': '6',
   'properties': {}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [10.364871, 43.713542]},
   'id': '7',
   'properties': {}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [10.362811, 43.741825]},
   'id': '8',
   'properties': {}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [10.372423, 43.765136]},
   'id': '9',
   'properties': {}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [10.402631, 43.769103]},
   'id': '10',
   'properties': {}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [10.404004, 43.683259]},
   'id': '11',
   'properties': {}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [10.425287, 43.745793]},
   'id': '12',
   'properties': {}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [10.33123, 43.829566]},
   'id': '13',
   'properties': {}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [10.312006, 43.718505]},
   'id': '14',
   'properties': {}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [10.306514, 43.774061]},
   'id': '15',
   'properties': {}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [10.325051, 43.683259]},
   'id': '16',
   'properties': {}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [10.395765, 43.708082]},
   'id': '17',
   'properties': {}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [10.340842, 43.708082]},
   'id': '18',
   'properties': {}},
  {'type': 'Feature',
   'geometry': {'type': 'Point', 'coordinates': [10.337409, 43.732399]},
   'id': '19',
   'properties': {}},
  {'type': 'Feature',
   'geometry': {'type': 'Polygon',
    'coordinates': [[[10.432153, 43.73736],
      [10.437645, 43.73736],
      [10.437645, 43.73984],
      [10.432153, 43.73984],
      [10.432153, 43.73736]]]},
   'id': '20',
   'properties': {}},
  {'type': 'Feature',
   'geometry': {'type': 'Polygon',
    'coordinates': [[[10.33123, 43.762656],
      [10.333976, 43.762656],
      [10.333976, 43.765136],
      [10.33123, 43.765136],
      [10.33123, 43.762656]]]},
   'id': '21',
   'properties': {}},
  {'type': 'Feature',
   'geometry': {'type': 'Polygon',
    'coordinates': [[[10.417735, 43.684252],
      [10.430093, 43.681273],
      [10.42872, 43.687728],
      [10.420481, 43.6917],
      [10.417735, 43.684252]]]},
   'id': '22',
   'properties': {}},
  {'type': 'Feature',
   'geometry': {'type': 'Polygon',
    'coordinates': [[[10.36899, 43.686238],
      [10.372423, 43.686238],
      [10.372423, 43.688225],
      [10.36899, 43.688225],
      [10.36899, 43.686238]]]},
   'id': '23',
   'properties': {}},
  {'type': 'Feature',
   'geometry': {'type': 'Polygon',
    'coordinates': [[[10.361438, 43.702126],
      [10.364871, 43.702126],
      [10.364871, 43.704111],
      [10.361438, 43.704111],
      [10.361438, 43.702126]]]},
   'id': '24',
   'properties': {}},
  {'type': 'Feature',
   'geometry': {'type': 'Polygon',
    'coordinates': [[[10.375169, 43.740833],
      [10.378602, 43.740833],
      [10.378602, 43.742321],
      [10.375169, 43.742321],
      [10.375169, 43.740833]]]},
   'id': '25',
   'properties': {}},
  {'type': 'Feature',
   'geometry': {'type': 'Polygon',
    'coordinates': [[[10.35114, 43.733391],
      [10.354573, 43.733391],
      [10.354573, 43.735375],
      [10.35114, 43.735375],
      [10.35114, 43.733391]]]},
   'id': '26',
   'properties': {}},
  {'type': 'Feature',
   'geometry': {'type': 'Polygon',
    'coordinates': [[[10.434212, 43.726941],
      [10.436272, 43.726941],
      [10.436272, 43.728429],
      [10.434212, 43.728429],
      [10.434212, 43.726941]]]},
   'id': '27',
   'properties': {}},
  {'type': 'Feature',
   'geometry': {'type': 'Polygon',
    'coordinates': [[[10.340155, 43.766623],
      [10.343588, 43.766623],
      [10.343588, 43.767615],
      [10.340155, 43.767615],
      [10.340155, 43.766623]]]},
   'id': '28',
   'properties': {}},
  {'type': 'Feature',
   'geometry': {'type': 'Polygon',
    'coordinates': [[[10.499434, 43.738352],
      [10.502181, 43.738352],
      [10.502181, 43.73984],
      [10.499434, 43.73984],
      [10.499434, 43.738352]]]},
   'id': '29',
   'properties': {}},
  {'type': 'Feature',
   'geometry': {'type': 'Polygon',
    'coordinates': [[[10.33123, 43.790916],
      [10.333289, 43.790916],
      [10.333289, 43.791907],
      [10.33123, 43.791907],
      [10.33123, 43.790916]]]},
   'id': '30',
   'properties': {}},
  {'type': 'Feature',
   'geometry': {'type': 'Polygon',
    'coordinates': [[[10.44451, 43.66687],
      [10.450003, 43.66687],
      [10.450003, 43.670844],
      [10.44451, 43.670844],
      [10.44451, 43.66687]]]},
   'id': '31',
   'properties': {}},
  {'type': 'Feature',
   'geometry': {'type': 'Polygon',
    'coordinates': [[[10.327797, 43.661903],
      [10.327797, 43.661903],
      [10.329857, 43.661903],
      [10.329857, 43.661903],
      [10.327797, 43.661903]]]},
   'id': '32',
   'properties': {}}]})

In [3]:
lucas = ee.FeatureCollection('JRC/LUCAS_HARMO/THLOC/V1')\
  .select(['point_id', 'lu1'])\
    .limit(1000)

# reclassify lucas data lc names
df = pd.read_csv('lucas_legends.csv', sep=';', error_bad_lines=False)
df['code'] = df['code'].str.strip("'").astype(str)

df_filter = df[(df['var'] == 'lu1') | (df['var'] == 'lu1_type')]

df_code = ee.List(df_filter['code'].tolist())
df_label = ee.List(df_filter['label'].tolist())

# Map over the 'lucas' Feature Collection
lucas = lucas.map(lambda ft: ft.set('lu1Name', df_label.get(
    df_code.indexOf(ft.get('lu1')))))

lucas_df = geemap.ee_to_pandas(lucas)
lucas_df

                                               lu1Name  point_id   lu1
0                                    'Nature reserves'  26821966  U364
1                                    'Nature reserves'  27462144  U364
2                                    'Nature reserves'  27542146  U364
3                                    'Water transport'  27482146  U313
4                                    'Abandoned areas'  26741958  U410
..                                                 ...       ...   ...
995  'Agriculture (excluding fallow land and kitche...  28742448  U111
996  'Agriculture (excluding fallow land and kitche...  27942398  U111
997  'Agriculture (excluding fallow land and kitche...  28002400  U111
998  'Agriculture (excluding fallow land and kitche...  28442422  U111
999  'Agriculture (excluding fallow land and kitche...  27722296  U111

[1000 rows x 3 columns]